import { PLACES } from './Const';

export const CATEGORY_ICONS = [
    { name: 'Pagami',                   route: 'pagami',                    type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.PAGAMI},
    { name: 'Tienda',                   route: 'tienda',                    type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.STORE},
    { name: 'Abasto',                   route: 'abasto',                    type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.STORE},
    { name: 'Barbería y Peluquería',    route: 'barberia_y_peluqueria',     type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.BEAUTY},
    { name: 'Café',                     route: 'cafe',                      type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.FOOD},
    { name: 'Casino',                   route: 'casino',                    type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.ENTERTAINMENT},
    { name: 'Comercio de Vehículos',    route: 'comercio_de_vehiculos',     type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.STORE},
    { name: 'Comida Rapida',            route: 'comida_rapida',             type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.FOOD},
    { name: 'Estacionamiento',          route: 'estacionamiento',           type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SERVICE},
    { name: 'Farmacia',                 route: 'farmacia',                  type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.SHOP},
    { name: 'Frutería',                 route: 'fruteria',                  type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.STORE},
    { name: 'Fábrica',                  route: 'fabrica',                   type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.INDUSTRY},
    { name: 'Gimnasio',                 route: 'gimnasio',                  type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SPORT},
    { name: 'Heladería',                route: 'heladeria',                 type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.FOOD},
    { name: 'Hotel',                    route: 'hotel',                     type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.HOTELERY},
    { name: 'Negocio de Bebidas',       route: 'negocio_de_bebidas',        type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.FOOD},
    { name: 'Negocio Temporal',         route: 'negocio_temporal',          type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.FOOD},
    { name: 'Odontología',              route: 'odontologia',               type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.STORE},
    { name: 'Panadería',                route: 'panaderia',                 type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.FOOD},
    { name: 'Perfumería',               route: 'perfumeria',                type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.SHOP},
    { name: 'Piscina',                  route: 'piscina',                   type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SPORT},
    { name: 'Pizzería',                 route: 'pizzeria',                  type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.FOOD},
    { name: 'Restaurante',              route: 'restaurante',               type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.FOOD},
    { name: 'Servicio de Grúas',        route: 'servicio_de_gruas',         type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SERVICE},
    { name: 'Servicio de Reparación',   route: 'servicio_de_reparacion',    type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SERVICE},
    { name: 'Servicio de Tatuajes',     route: 'servicio_de_tatuajes',      type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SERVICE},
    { name: 'Servicio Técnico',         route: 'servicio_tecnico',          type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SERVICE},
    { name: 'Servicios Medicos',        route: 'servicios_medicos',         type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.MEDICINE},
    { name: 'Taller',                   route: 'taller',                    type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SERVICE},
    { name: 'Taxi',                     route: 'taxi',                      type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.SERVICE},
    { name: 'Tienda de Deportes',       route: 'tienda_deporte',            type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.SHOP},
    { name: 'Tienda de Motos',          route: 'tienda_motos',              type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.SHOP},
    { name: 'Tienda de Pinturas',       route: 'tienda_pinturas',           type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.SHOP},
    { name: 'Tienda de Ropas',          route: 'tienda_ropa',               type: PLACES.TYPE.STORE ,       subCategory: PLACES.CATEGORY.SHOP},
    { name: 'Veterinario',              route: 'veterinario',               type: PLACES.TYPE.SERVICE ,     subCategory: PLACES.CATEGORY.MEDICINE},
];
